name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13


      - name: Build
        run: hugo --minify
      - name: Update search index
        run: |
          curl -H "X-TYPESENSE-API-KEY: ${{ secrets.TYPESENSE_KEY }}" \
          -X DELETE \
          "https://typesense.tgc54.com/collections/blog"

          curl "https://typesense.tgc54.com/collections" \
          -X POST \
          -H "Content-Type: application/json" \
          -H "X-TYPESENSE-API-KEY: ${{ secrets.TYPESENSE_KEY }}" \
          -d '{
              'name': 'blog',
              'fields': [
                {'name': 'title', 'type': 'string' },
                {'name': 'contents', 'type': 'string' },
              ]
          }'
          
          curl -H "X-TYPESENSE-API-KEY: ${{ secrets.TYPESENSE_KEY }}" \
          -X POST --data-binary @./public/index.jsonl \
          "https://typesense.tgc54.com/collections/blog/documents/import?action=create"


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
